meta_product_name: "Code_with_us"
meta_title: "Code_with_us - Connect, Collaborate, Code, Create"
meta_description: "Helping coders to get together "
meta_image: "../app/assets/images/final_code_with_us_logo.png"
